name: BabyBot Application Deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest   
    steps:
    - uses: actions/checkout@v2
    - name: Gradle Caching
      uses: actions/cache@v3
      with:
        path: |  
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
      
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      shell: bash          
      
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
      
    - name: build java
      run: ./gradlew clean build
      shell: bash
