name: BabyBot Application Deploy

on:
  workflow_dispatch:
    inputs:
      name:
        description: "RELEASE"
        required: true
        default: "release v0.1"
jobs:
  build:
    runs-on: ubuntu-latest   
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
        
    - name: execute gradle
      run: chmod +x ./gradlew
      
    - name: build java
      run: ./gradlew clean build
      
    - name: find jar
      run: ls -la | ls -la ./build/libs/*

    - name: ssh Jar
      uses: appleboy/scp-action@master  
      with:
          host: ${{ secrets.DEPLOY_IP }}
          username: ${{ secrets.ID }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "build/libs/gunnu-bot-1.0.0.jar"
          target: "/home/ubuntu/baby-bot"
          
    - name: ssh dockerfile
      uses: appleboy/scp-action@master  
      with:
          host: ${{ secrets.DEPLOY_IP }}
          username: ${{ secrets.ID }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "join/dockerfile"
          target: "/home/ubuntu/baby-bot"
          
    - name: deploy app
      uses: appleboy/ssh-action@v0.1.6
      with:
          host: ${{ secrets.DEPLOY_IP }}
          username: ${{ secrets.ID }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo sh baby-bot/deploy.sh          
